# Generated by Django 3.0.8 on 2020-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.ImageField(upload_to='tv/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон в формате +1234567890')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Конфигурация контактов',
                'verbose_name_plural': 'Конфигурация контактов',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massege', models.TextField(verbose_name='Сообщение')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('status', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Связь с нами',
                'verbose_name_plural': 'Сообщения со страницы связь с нами',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.CharField(max_length=30, verbose_name='Название')),
                ('massage', models.TextField(verbose_name='Приставка и тариф')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('status', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Заявка на подключение',
                'verbose_name_plural': 'Заявки на подключение',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Длительность подписки')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='sub_image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Абонимент',
                'verbose_name_plural': 'Абонименты',
            },
        ),
        migrations.CreateModel(
            name='TvBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('stone', models.CharField(max_length=30, verbose_name='Процессор')),
                ('video_size', models.CharField(max_length=30, verbose_name='Разрешение')),
                ('graphics', models.CharField(blank=True, max_length=30, verbose_name='Графика')),
                ('memory', models.CharField(max_length=30, verbose_name='Память')),
                ('ports', models.CharField(max_length=30, verbose_name='Интерфейсы')),
                ('wi_fi', models.CharField(max_length=150, verbose_name='WiFi')),
                ('image', models.ImageField(upload_to='box_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Приставка',
                'verbose_name_plural': 'Приставки',
            },
        ),
    ]
